### ISSUE TITLE
Task - prefetch dependency - cachi2 fails: go: download go1.22 for linux/amd64: toolchain not available

### ISSUE THREAD

**Issue by cmoulliard** [konflux-ci/build-definitions#1477]
## Issue

The task - prefetch dependency which uses cachi2 fails and reports such an error
```
step-sanitize-cachi2-config-file-with-yq

step-prefetch-dependencies
INFO: Using mounted CA bundle: /mnt/trusted-ca/ca-bundle.crt
'/mnt/trusted-ca/ca-bundle.crt' -> '/etc/pki/ca-trust/source/anchors/ca-bundle.crt'
2024-09-26 16:59:53,012 INFO Fetching the gomod dependencies at subpath pack
2024-09-26 16:59:53,012 INFO Fetching the gomod dependencies at the "pack" directory
2024-09-26 16:59:53,315 ERROR The command "go env GOWORK" failed
2024-09-26 16:59:53,315 ERROR STDERR:
go: downloading go1.22 (linux/amd64)
go: download go1.22 for linux/amd64: toolchain not available
2024-09-26 16:59:53,322 ERROR PackageManagerError: Go execution failed: `go env GOWORK` failed with rc=1
Error: PackageManagerError: Go execution failed: `go env GOWORK` failed with rc=1
  The cause of the failure could be:
  - something is broken in Cachi2
  - something is wrong with your repository
  - communication with an external service failed (please try again)
```
using the PipelineRun of this project: https://github.com/redhat-buildpacks/paketo-container/
Tenant:https://console.redhat.com/application-pipeline/workspaces/cmoullia

Discussion with Bruno Apimentel & Charles

You should specify it as 1.22.x. Or check the full docs on this: https://spaces.redhat.com/pages/viewpage.action?pageId=228017926#UpstreamSources(Cachito,ContainerFirst)-Go1.21+

cmoullia
  Yesterday at 8:01 PM
I dont think that I can change such a value as part of the git submodule imported : [https://github.com/buildpacks/pack/blob/4ffdb5e09c7c1c42f0d1d17de65d0f39bc8d517f/go.mod#L146https://github.com/build[…]de65d0f39bc8d517f/go.mod#L146](https://github.com/buildpacks/pack/blob/4ffdb5e09c7c1c42f0d1d17de65d0f39bc8d517f/go.mod#L146https://github.com/buildpacks/pack/blob/4ffdb5e09c7c1c42f0d1d17de65d0f39bc8d517f/go.mod#L146)

bpimente
  Yesterday at 8:21 PM
There's no immeditate workaround on Cachi2's side either :confused:
I'll need to bring this to the team to see if there's something that can be done on our side.

@brunoapimentel

**Comment by chmeliik** [comment]
If I understand correctly, this is either misconfiguration in the source repository or an issue with cachi2. If it is the latter, please open an issue in https://github.com/containerbuildsystem/cachi2

**Comment by eskultety** [comment]
For completeness and bookkeeping @cmoulliard opened: https://github.com/buildpacks/pack/issues/2267 which will determine the outcome on this in the short term.

**Comment by cmoulliard** [comment]
> For completeness and bookkeeping @cmoulliard opened: [buildpacks/pack#2267](https://github.com/buildpacks/pack/issues/2267) which will determine the outcome on this in the short term.

Take care that even if paketo community fixes it upstream for `pack` CLI/Tool, many others paketo projects that we will use as input to build images could generate also such a cachi2 problem. So ideally, cachi2 should become more flexible regarding to the version ot be used about toolchain, etc
