### ISSUE TITLE
Allow `task/sast-snyk-check` to create a monitoring project

### ISSUE THREAD

**Issue by pierDipi** [konflux-ci/build-definitions#1489]
See https://docs.snyk.io/snyk-cli/commands/monitor#description

We're injecting our team org ID (`--org=<x>`) and we would like to continuously monitor the project for new vulnerabilities even when there are no changes to the repository while also having a dashboard to summarize, browse and triage security issues.

The current task is running `snyk code test`

https://github.com/konflux-ci/build-definitions/blob/abd17995f07dfc3cfe79ba4d55a9575f63b986eb/task/sast-snyk-check/0.2/sast-snyk-check.yaml#L78

Using the `--report` flag for `snyk code test` is only available for "Enterprise customer **and** in the Publish CLI results Closed Beta" ([ref](https://docs.snyk.io/snyk-cli/commands/code-test#report)) and I'm not sure if we're or not, if not, the task would need to optionally (configurable) use `snyk monitor`

**Comment by chmeliik** [comment]
@konflux-ci/integration-service-maintainers I believe this should be achievable, right?

**Comment by pierDipi** [comment]
Actually, I missed this line, I guess we will need to wait for the `--monitor` flag to get out of the beta phase
> The monitor command is not supported for Snyk Code.
