### ISSUE TITLE
Clair scan overwritten

### ISSUE THREAD

**Issue by cardil** [konflux-ci/build-definitions#1632]
The `>` redirection overwrites the previous report, right? The `>>` redirection should be used if the intention was to append, as the comment implies.

See: 

https://github.com/konflux-ci/build-definitions/blob/51cb7249f1a48a92d0098560aa418bb2025c1659/task/clair-scan/0.2/clair-scan.yaml#L114-L115

**Comment by zregvart** [comment]
One invocation pipes to `clair-result-$2.json` and the other to `clair-report-$2.json`, different files.
